# Generated by Django 4.0.5 on 2022-06-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_todoitem_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['priority', 'due_date']},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('2', 'High'), ('1', 'Medium'), ('0', 'Low')], default='1', max_length=30),
        ),
    ]
