# Generated by Django 4.0.5 on 2022-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_todoitem_options_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-priority', 'due_date']},
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=30),
        ),
    ]
